# Earthworm Docker Sandbox CI
image: debian:buster-slim

services:
  - docker:19.03.1-dind

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GIT_SUBMODULES: recursive
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# Run preliminary commands
before_script:
  # Display system info
  - apt-get clean && apt-get update && apt-get install -y make curl && apt-get clean
    ##########################################################
    # Install docker
    # https://docs.docker.com/engine/install/debian/
    ##########################################################
  - apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  - add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io
    ##########################################################
  - uname -a
  - make --version
  - docker --version
  - make check_required_commands

build:
  stage: build
  script:
    - make build

# cache:
# paths:
# - dump/

