version: '2'

networks:
  ew:

services:

  hew:
    container_name: hew
    # image: ew-sandbox:d59707fc
    # image: ew-sandbox:a4bb3e30
    image: ew-sandbox:a7e23e8e
    command: /opt/scripts/ew_startstop_trap_pau.sh
    ports:
    # export wave server ports
      - 16021-16044:16021-16044
    # import/export generic ports
      - 19001-19010:19001-19010
    # export winston scnl ports
      - 16001-16006:16001-16006
    environment:
      - EW_HOSTNAME=hew
    volumes:
      - ${EW_RUN_DIR}:/opt/ew_env:consistent
      # - $EW_PARAMS:/opt/ew_env/params:consistent
      # - $EW_LOG:/opt/ew_env/log:consistent
      - $EW_MAINDIREWSPACE:$EW_MAINDIREWSPACE:consistent
      - $EW_MAINDIRWAVESERVER:$EW_MAINDIRWAVESERVER:consistent
      - /home/ew/snwclient:/home/ew/snwclient:consistent
    restart: unless-stopped

    networks:
      - ew


