#!/bin/bash

echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"
echo ""
echo "Istruzioni rapide il per controllo tramite 'docker compose' di Earthworm"
echo ""
echo "In sostanza c\'e\' solo un passaggio in più dopo il login SSH, ovverodi eseguire"
echo "  il comandi tramite 'docker' o 'docker compose', per il resto rimane tutto uguale."
echo ""
echo "Innazitutto eseguire rt:"
echo ""
echo "    $ rt"
echo ""
echo "Poi cambiare directory:"
echo ""
echo "    $ cd ~/gitwork/_earthworm/earthworm-docker-sandbox"
echo ""
echo "E' attivo un solo docker container con nome uguale al servizio, ovvero 'hew'."
echo ""
echo "Avviare il servizio:"
echo ""
echo "    $ docker compose up -d"
echo ""
echo "Verificare il docker container se attivo:"
echo ""
echo "    $ docker compose ps"
echo ""
echo "Aprire una shell bash nel container in cui gira earthworm per poi eseguire comandi interattivamente:"
echo ""
echo "    $ docker compose exec hew bash"
echo ""
echo "Eseguire direttamente un comando all'interno del container 'hew', ad esempio status."
echo ""
echo "    $ docker compose exec hew bash -i -c 'status'"
echo ""
echo "Chiudere e rimuovere il container in maniera pulita:"
echo ""
echo "    $ docker compose stop -t 120 && docker compose down"
echo ""
echo "Nota: l'opzione -t 120 è importante poiché permette di chiudere "
echo "      maniera pulita Earthworm attendendo che starstop si chiuda."
echo "      Nella versione 1.8 di docker compose non e' disponibile l'opzione -t"
echo "      per il comando 'docker down', quindi se si vuole chiudere e"
echo "      rimuovere il container bisogna eseguire i comandi in cascata."
echo ""
echo "E' possibile accedere al container da qualsiasi directory anche tramite il comando 'docker':"
echo ""
echo "    $ docker exec -it hew bash"
echo ""
echo "    $ docker exec -it hew bash -i -c 'status'"
echo ""
echo "Per visualizzare questo help eseguire:"
echo ""
echo "    $ ew_docker_help"
echo ""
echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"
